name: Sport Text Classification ML Workflow

on:
  workflow_dispatch:
    inputs:
      epochs:
        description: 'Epochs'
        required: true
        default: '10'
      lr:
        description: 'Learning rate'
        required: true
        default: '0.01'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy gensim torch

      - name: Download word2vec embeddings (zip)
        run: |
          wget https://github.com/sdadas/polish-nlp-resources/releases/download/v1.0/word2vec.zip
          unzip word2vec.zip

      - name: Clone sport-text-classification repo
        run: |
          git clone https://git.wmi.amu.edu.pl/kubapok/sport-text-classification-ball-ISI-public.git
          mv sport-text-classification-ball-ISI-public/* .
          rm -rf sport-text-classification-ball-ISI-public

      - name: Unpack train.tsv.gz
        run: |
          gunzip -f train/train.tsv.gz || echo "Already unpacked"

      - name: Train model
        run: |
          python src/train.py ${{ github.event.inputs.epochs }} ${{ github.event.inputs.lr }}

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.pth

  evaluate:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy gensim

      - name: Download word2vec embeddings (zip)
        run: |
          wget https://github.com/sdadas/polish-nlp-resources/releases/download/v1.0/word2vec.zip
          unzip word2vec.zip

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model

      - name: Evaluate model
        run: |
          python src/eval.py
